### ISSUE TITLE
[Warning] InvalidMessageError: BUFFER_SHORTAGE

### ISSUE THREAD

**Issue by ansien** [SocketCluster/sc-codec-min-bin#1]
Getting this error from Node about 20 seconds after connecting to my server and sending a test message. Any ideas?

```
1489785306809 - Origin: Worker (PID 2836)
   [Warning] InvalidMessageError: BUFFER_SHORTAGE
    at DecodeBuffer.reserve (C:\Users\me\Documents\Projects\someiogame\server\node_modules\msgpack-lite\lib\flex-buffer.js:64:41)
    at uint8 (C:\Users\me\Documents\Projects\someiogame\server\node_modules\msgpack-lite\lib\read-format.js:117:23)
    at Codec.decode (C:\Users\me\Documents\Projects\someiogame\server\node_modules\msgpack-lite\lib\read-core.js:22:16)
    at DecodeBuffer.fetch (C:\Users\me\Documents\Projects\someiogame\server\node_modules\msgpack-lite\lib\decode-buffer.js:26:21)
    at DecodeBuffer.read (C:\Users\me\Documents\Projects\someiogame\server\node_modules\msgpack-lite\lib\flex-buffer.js:166:28)
    at Object.decode (C:\Users\me\Documents\Projects\someiogame\server\node_modules\msgpack-lite\lib\decode.js:10:18)
    at Object.module.exports.decode (C:\Users\me\Documents\Projects\someiogame\server\node_modules\sc-codec-min-bin\index.js:116:24)
    at Emitter.SCSocket.decode (C:\Users\me\Documents\Projects\someiogame\server\node_modules\socketcluster-server\scsocket.js:247:28)
    at WebSocket.internalOnMessage (C:\Users\me\Documents\Projects\someiogame\server\node_modules\socketcluster-server\scsocket.js:84:18)
    at onServerMessage (C:\Users\me\Documents\Projects\someiogame\server\node_modules\uws\uws.js:14:15)
```

**Comment by ansien** [comment]
Sorry, i'm retarted, had an older client sending messages.
